### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [Shyguy99/Insider#12]
Hello there,
I would like to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal. Kindly assign me this issue as a part of DWOC.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by himanshu007-creator** [comment]
I can work on this issue. Please assign me.

**Comment by Shyguy99** [comment]
@muthuannamalai12 Thanks for your time and contribution. I am assigning this to you
