### ISSUE TITLE
Adding a seperate line for admin in readme.md file and creating a Contributors table which updates automatically.

### ISSUE THREAD

**Issue by Swastik1710** [Shyguy99/Insider#14]
As of now , the Contributors table in the Readme.md file is hardcoded and hence not up to date. One needs to update it manually each and every time. I wanna automate this task by adding a new Contributors table which will update on it's own.
Moreover , I wanna add a separate line to showcase the project Admin if you want.

**Comment by Swastik1710** [comment]
Can you please assign this to me ?
Thank you !

**Comment by Shyguy99** [comment]
@Swastik1710 Thanks for your time and contribution to the project. You can add both  the points you mentioned.
Assigning this issue to you....

**Comment by Swastik1710** [comment]
Hey @Shyguy99, thank you for assigning this to me.
But i think you've closed this issue mistakenly.

**Comment by Swastik1710** [comment]
Hey @Shyguy99, you've assigned this issue to someone else though I've created this issue 18 days ago.
