### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by muthuannamalai12** [Shyguy99/Insider#15]
I would like to add a CONTRIBUTING.mdfile which will contain all contributing guidelines and all git workflow so that all newbies or beginners and even experts can look into it and also the contributors will understand the workflow

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by Shyguy99** [comment]
Ok I am assigning this to  you. 
Thanks for your  contribution.
