### ISSUE TITLE
Add DWoC as open source Event

### ISSUE THREAD

**Issue by PinRathod** [Shyguy99/Insider#19]
This project is part of DWoC open source event.It should be mention in README file.

**Comment by PinRathod** [comment]
Can I work on this?

**Comment by Shyguy99** [comment]
Ok.

**Comment by PinRathod** [comment]
@Shyguy99 My point is not updated on leaderboard yet. Please assign my point.

**Comment by Shyguy99** [comment]
Wait for it to update till tomorrow night!!

**Comment by Shyguy99** [comment]
@PinRathod Please wait for it to update till tomorrow night
