### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [Shyguy99/Insider#3]
Hi @Shyguy99 

I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by Shyguy99** [comment]
Thanks for giving your time and contribution to this project. I appreciate it. 
Kindly explain what do you mean by DWOC and Level label
Thank You.

**Comment by akrish4** [comment]
thank you for assigning
kindly do add the DWOC and Level-3  or Level-4 label @Shyguy99

this is a nice and new feature for this repo , kindly note this point @Shyguy99

**Comment by akrish4** [comment]
#10   PR
