### ISSUE TITLE
CONTRIBUTING FILE 

### ISSUE THREAD

**Issue by akrish4** [Shyguy99/Insider#4]
Hi @Shyguy99 
I would like to contribute to this amazing project 
I would like to add a `CONTRIBUTING.md`file which will contain all contributing guidelines and all git workflow so that all newbies or beginers and even experts can look into into it and also the contributors will understand the workflow 

Kindly do assign me 

Kindly add the labels also

**Comment by akrish4** [comment]
thank you for assigning
kindly do add the DWOC and Level-2  or Level-3 label @Shyguy99

**Comment by muthuannamalai12** [comment]
@Shyguy99 I can see this issue has not been resolved yet and the issue made is also closed by the assignee. So can I give it a try? as a part of DWOC.
